### ISSUE TITLE
move over the contents of the newsletter page

### ISSUE THREAD

**Issue by Iconians** [rolandagency/react-2024#13]
this is mainly moving the html over and styling similar to what was done previously

**Comment by Rahnken** [comment]
Do you want this to be what is currently in the release-2024 html or the example document that Monica made for the discord?

**Comment by Iconians** [comment]
That is a good question, looking at the vanilla site you can use your judgment on what can be made closer to reflect the example Monica gave us, the side column for sure could look closer to the example, I haven't seen any material from the clients for the newsletter format but use your best judgment in making it closer to her design
